### ISSUE TITLE
Crashes when there is no .swiftlint.yml in home directory

### ISSUE THREAD

**Issue by garrett-davidson** [norio-nomura/ExtraBuildPhase#4] opened 2016-05-15 22:59 UTC
If the user building the project doesn't have a .swiftlint.yml in their home directory, ExtraBuildPhase crashes

**Comment by norio-nomura** [comment] 2016-05-16 11:42
Thanks for reporting.
Sorry, the issue is caused by the script that ExtraBuildPhase generates.
For workaround, you can customize the script as following configuration:

``` console
defaults write io.github.norio-nomura.ExtraBuildPhase shellScript -string '
if which swiftlint >/dev/null; then
    [ -f .swiftlint.yml ] && CONFIG="--config .swiftlint.yml" || [ -f $HOME/.swiftlint.yml ] && CONFIG="--config $HOME/.swiftlint.yml"
    swiftlint lint --quiet --use-script-input-files $CONFIG
fi
exit 0 # ignore result of swiftlint
'
```

Running clean build is required for taking effect of the configuration.

**Comment by norio-nomura** [comment] 2016-05-28 15:03
Fixed by https://github.com/norio-nomura/ExtraBuildPhase/releases/tag/0.3.5

**Closed as completed by norio-nomura** 2016-05-28 15:03 UTC
Labels: bug
